### ISSUE TITLE
Add more descriptive titles instead of the default

### ISSUE THREAD

**Issue by jubar** [jubar/ember-montevideo-app#20]
<img width="488" alt="screen shot 2017-04-27 at 13 10 38" src="https://cloud.githubusercontent.com/assets/1234695/25493264/ef4bd864-2b4b-11e7-932c-f89d9a43b65b.png">

**Comment by san650** [comment]
It would be great if the favicon includes a countdown of the days left to the next meetup.

I envision the Montevideo Tomster plus the number of days left 😛 . Similar to this

<img width="173" alt="screen shot 2017-04-27 at 3 22 03 pm" src="https://cloud.githubusercontent.com/assets/1234607/25498148/59ebf080-2b5d-11e7-81aa-46e1f5a017aa.png">
