### ISSUE TITLE
App is not working on chrome in Android

### ISSUE THREAD

**Issue by jubar** [jubar/ember-montevideo-app#21]
When we enter to the site, we only see a blank screen

**Comment by san650** [comment]
I think it's the integrity check on the js files.

When Chrome on Android access the page it downloads an "optimized" version of the file (pre-processed by google) so the integrity check fails 😭

**Comment by jubar** [comment]
I disabled SRI in ember-cli-build. We can enable this feature when we'll set up HTTPS.

I close the issue for now, since it is working on Chrome in Android
